name: Build

on:
  workflow_dispatch: ~
  push:
    branches:
      - main
    paths:
      - index.ts

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: wdzeng/action-of-action@v1
